import {
  UserProfile,
  SubjectItem,
  TaskItem,
  MilestoneItem,
  TeamItem,
  TeamMemberItem,
  DiscussionMessage,
  TeamActivityItem,
  ResourceItem,
  NotificationItem,
} from './database.types';

export const INITIAL_USER: UserProfile = {
  id: 'user_sahil_01',
  name: 'Sahil Doe',
  email: 'sahil@university.edu',
  avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  bio: 'Computer Science student focusing on Applied AI, IoT systems, and Mathematics. Passionate about collaborative peer study and building practical technology.',
  institution: 'National Institute of Technology',
  course: 'B.Tech Computer Science & Engineering',
  academic_year: 'Year 3, Semester 6',
  location: 'Bangalore, India',
  timezone: 'Asia/Kolkata (IST)',
  skills: ['Python', 'C / C++', 'Web Development', 'IoT', 'Linear Algebra', 'Calculus', 'Data Structures'],
  interests: ['Machine Learning', 'Embedded Systems', 'Robotics', 'Open Source', 'Competitive Programming'],
  streak_days: 5,
  created_at: '2026-01-15T08:00:00Z',
  updated_at: '2026-09-27T10:00:00Z',
};

export const INITIAL_SUBJECTS: SubjectItem[] = [
  {
    id: 'subj_math',
    user_id: 'user_sahil_01',
    name: 'Engineering Mathematics',
    current_topic: 'Fourier Series & Integration',
    confidence_score: 2,
    category: 'Core Engineering',
    color: '#D88E75',
    created_at: '2026-08-01T09:00:00Z',
  },
  {
    id: 'subj_physics',
    user_id: 'user_sahil_01',
    name: 'Applied Physics',
    current_topic: 'Thermodynamics & Optics',
    confidence_score: 4,
    category: 'Applied Sciences',
    color: '#92A390',
    created_at: '2026-08-01T09:00:00Z',
  },
  {
    id: 'subj_cs',
    user_id: 'user_sahil_01',
    name: 'Computer Architecture',
    current_topic: 'Pipelining & Cache Memory',
    confidence_score: 3,
    category: 'Computer Science',
    color: '#354E6B',
    created_at: '2026-08-01T09:00:00Z',
  },
];

export const INITIAL_TEAMS: TeamItem[] = [
  {
    id: 'team_maths_survivors',
    name: 'Maths Survivors',
    description: 'Collaborative peer learning group dedicated to conquering Engineering Mathematics, Fourier Transforms, and Differential Calculus.',
    goal: 'Score 90%+ in Mathematics Internal Assessment (October 3)',
    project_topic: 'Mathematics Internal Prep',
    category: 'Mathematics',
    join_code: 'MATH-7821',
    visibility: 'discoverable',
    owner_id: 'user_sahil_01',
    owner_name: 'Sahil Doe',
    max_members: 6,
    member_count: 3,
    progress_pct: 72,
    status: 'active',
    tags: ['Calculus', 'Fourier Series', 'Problem Solving', 'Peer Learning'],
    created_at: '2026-09-10T14:30:00Z',
  },
  {
    id: 'team_smart_agri',
    name: 'Smart Agriculture Research',
    description: 'IoT and Computer Vision based soil moisture sensing and automated greenhouse irrigation system prototype.',
    goal: 'Complete hardware testing and research paper draft by mid-November.',
    project_topic: 'IoT & Edge AI',
    category: 'Capstone Project',
    join_code: 'AGRI-4092',
    visibility: 'discoverable',
    owner_id: 'user_arun_02',
    owner_name: 'Arun Kumar',
    max_members: 5,
    member_count: 4,
    progress_pct: 64,
    status: 'active',
    tags: ['IoT', 'Research', 'AI', 'Embedded'],
    created_at: '2026-09-05T11:00:00Z',
  },
  {
    id: 'team_algo_masters',
    name: 'Algorithm Study Cohort',
    description: 'Weekly LeetCode sprint and dynamic programming study group preparing for upcoming summer internship technical interviews.',
    goal: 'Solve 150 Hard/Medium interview questions collectively.',
    project_topic: 'Algorithms & Data Structures',
    category: 'Interview Prep',
    join_code: 'ALGO-9912',
    visibility: 'discoverable',
    owner_id: 'user_priya_04',
    owner_name: 'Priya Sharma',
    max_members: 8,
    member_count: 5,
    progress_pct: 55,
    status: 'active',
    tags: ['Algorithms', 'Python', 'C++', 'Interviews'],
    created_at: '2026-09-12T09:15:00Z',
  },
];

export const INITIAL_TEAM_MEMBERS: TeamMemberItem[] = [
  // Maths Survivors members
  {
    id: 'tm_1',
    team_id: 'team_maths_survivors',
    user_id: 'user_sahil_01',
    name: 'Sahil Doe (You)',
    email: 'sahil@university.edu',
    role: 'owner',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    joined_at: '2026-09-10T14:30:00Z',
    confidence_topics: [
      { topic: 'Integration', score: 2 },
      { topic: 'Differential Equations', score: 5 },
      { topic: 'Linear Algebra', score: 4 },
    ],
  },
  {
    id: 'tm_2',
    team_id: 'team_maths_survivors',
    user_id: 'user_arun_02',
    name: 'Arun Kumar',
    email: 'arun@university.edu',
    role: 'member',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    joined_at: '2026-09-11T10:00:00Z',
    confidence_topics: [
      { topic: 'Integration', score: 4 },
      { topic: 'Differential Equations', score: 2 },
      { topic: 'Vector Calculus', score: 4 },
    ],
  },
  {
    id: 'tm_3',
    team_id: 'team_maths_survivors',
    user_id: 'user_neha_03',
    name: 'Neha Roy',
    email: 'neha.roy@university.edu',
    role: 'member',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    joined_at: '2026-09-12T16:20:00Z',
    confidence_topics: [
      { topic: 'Integration', score: 3 },
      { topic: 'Differential Equations', score: 4 },
      { topic: 'Complex Variables', score: 5 },
    ],
  },
  // Smart Agri members
  {
    id: 'tm_4',
    team_id: 'team_smart_agri',
    user_id: 'user_arun_02',
    name: 'Arun Kumar',
    email: 'arun@university.edu',
    role: 'owner',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    joined_at: '2026-09-05T11:00:00Z',
    confidence_topics: [{ topic: 'Hardware & Circuits', score: 5 }],
  },
  {
    id: 'tm_5',
    team_id: 'team_smart_agri',
    user_id: 'user_sahil_01',
    name: 'Sahil Doe',
    email: 'sahil@university.edu',
    role: 'member',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    joined_at: '2026-09-06T14:10:00Z',
    confidence_topics: [{ topic: 'Embedded ML', score: 4 }],
  },
];

export const INITIAL_TASKS: TaskItem[] = [
  {
    id: 'task_01',
    user_id: 'user_sahil_01',
    team_id: 'team_maths_survivors',
    subject_id: 'subj_math',
    subject_name: 'Engineering Mathematics',
    title: 'Integration by Parts Problem Set',
    description: 'Complete questions 1 to 20 from Chapter 7, focusing on trigonometric substitution and partial fractions.',
    status: 'in_progress',
    priority: 'high',
    due_date: '2026-09-29T18:00:00Z',
    estimated_minutes: 45,
    assignee_id: 'user_sahil_01',
    assignee_name: 'Sahil Doe',
    assignee_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    completed_at: null,
    created_at: '2026-09-20T10:00:00Z',
  },
  {
    id: 'task_02',
    user_id: 'user_sahil_01',
    team_id: 'team_maths_survivors',
    subject_id: 'subj_physics',
    subject_name: 'Applied Physics',
    title: 'Physics Lab Record Submission',
    description: 'Document the Michelson Interferometer experiment with error analysis and wavelength verification.',
    status: 'done',
    priority: 'high',
    due_date: '2026-09-26T16:30:00Z',
    estimated_minutes: 60,
    assignee_id: 'user_sahil_01',
    assignee_name: 'Sahil Doe',
    assignee_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    completed_at: '2026-09-26T16:30:00Z',
    created_at: '2026-09-21T11:00:00Z',
  },
  {
    id: 'task_03',
    user_id: 'user_sahil_01',
    team_id: 'team_maths_survivors',
    subject_id: 'subj_math',
    subject_name: 'Engineering Mathematics',
    title: 'Finalize Team Presentation Slides',
    description: 'Coordinate with Arun and Neha on slide deck for Fourier series applications in audio signal filtering.',
    status: 'todo',
    priority: 'urgent',
    due_date: '2026-09-28T20:00:00Z',
    estimated_minutes: 30,
    assignee_id: 'user_neha_03',
    assignee_name: 'Neha Roy',
    assignee_avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    completed_at: null,
    created_at: '2026-09-22T09:30:00Z',
  },
  {
    id: 'task_04',
    user_id: 'user_sahil_01',
    team_id: 'team_maths_survivors',
    subject_id: 'subj_math',
    subject_name: 'Engineering Mathematics',
    title: 'Review Mock Test Question Paper',
    description: 'Verify 2025 previous year questions and review differential equations marking rubric.',
    status: 'review',
    priority: 'medium',
    due_date: '2026-09-30T15:00:00Z',
    estimated_minutes: 40,
    assignee_id: 'user_arun_02',
    assignee_name: 'Arun Kumar',
    assignee_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    completed_at: null,
    created_at: '2026-09-23T14:00:00Z',
  },
  {
    id: 'task_05',
    user_id: 'user_sahil_01',
    team_id: null,
    subject_id: 'subj_cs',
    subject_name: 'Computer Architecture',
    title: 'Cache Mapping & Hit Rate Analysis Notes',
    description: 'Summarize Direct-mapped vs 4-way set associative cache replacement policies.',
    status: 'done',
    priority: 'low',
    due_date: '2026-09-25T17:00:00Z',
    estimated_minutes: 35,
    assignee_id: 'user_sahil_01',
    assignee_name: 'Sahil Doe',
    assignee_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    completed_at: '2026-09-25T17:00:00Z',
    created_at: '2026-09-20T16:00:00Z',
  },
  {
    id: 'task_06',
    user_id: 'user_sahil_01',
    team_id: 'team_maths_survivors',
    subject_id: 'subj_math',
    subject_name: 'Engineering Mathematics',
    title: 'Differential Equations Formula Cheatsheet',
    description: 'Compile first-order linear and Bernoulli equation solution shortcuts for quick revision.',
    status: 'done',
    priority: 'medium',
    due_date: '2026-09-24T12:00:00Z',
    estimated_minutes: 25,
    assignee_id: 'user_sahil_01',
    assignee_name: 'Sahil Doe',
    assignee_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    completed_at: '2026-09-24T12:00:00Z',
    created_at: '2026-09-22T10:00:00Z',
  },
  {
    id: 'task_07',
    user_id: 'user_sahil_01',
    team_id: 'team_smart_agri',
    subject_id: null,
    subject_name: 'IoT Capstone',
    title: 'ESP32 Soil Moisture Sensor Calibration',
    description: 'Perform wet vs dry sensor reading calibration and log ADC values over 12 hours.',
    status: 'in_progress',
    priority: 'high',
    due_date: '2026-10-02T19:00:00Z',
    estimated_minutes: 50,
    assignee_id: 'user_sahil_01',
    assignee_name: 'Sahil Doe',
    assignee_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    completed_at: null,
    created_at: '2026-09-24T15:00:00Z',
  },
];

export const INITIAL_MILESTONES: MilestoneItem[] = [
  {
    id: 'mile_1',
    user_id: 'user_sahil_01',
    team_id: null,
    title: 'Planning & Syllabus Mapping',
    category: 'Foundations',
    status: 'completed',
    progress_pct: 100,
    due_date: '2026-09-10T23:59:59Z',
    completed_at: '2026-09-09T18:00:00Z',
    tasks_count: 5,
    completed_tasks_count: 5,
    description: 'Break down semester curriculum, map high-weightage topics, and identify initial knowledge gaps.',
    created_at: '2026-09-01T08:00:00Z',
  },
  {
    id: 'mile_2',
    user_id: 'user_sahil_01',
    team_id: null,
    title: 'Research & Core Concept Mastery',
    category: 'Academic Study',
    status: 'completed',
    progress_pct: 100,
    due_date: '2026-09-22T23:59:59Z',
    completed_at: '2026-09-22T19:30:00Z',
    tasks_count: 8,
    completed_tasks_count: 8,
    description: 'Complete comprehensive study notes for Applied Physics and Engineering Mathematics units 1 and 2.',
    created_at: '2026-09-10T08:00:00Z',
  },
  {
    id: 'mile_3',
    user_id: 'user_sahil_01',
    team_id: 'team_maths_survivors',
    title: 'Development & Problem Solving Sprint',
    category: 'Active Practice',
    status: 'in_progress',
    progress_pct: 72,
    due_date: '2026-10-02T23:59:59Z',
    completed_at: null,
    tasks_count: 10,
    completed_tasks_count: 7,
    description: 'Solve 100+ multi-step engineering calculus and differential equation problems with peer verification.',
    created_at: '2026-09-18T08:00:00Z',
  },
  {
    id: 'mile_4',
    user_id: 'user_sahil_01',
    team_id: 'team_maths_survivors',
    title: 'Testing & Mock Exam Simulations',
    category: 'Assessment',
    status: 'upcoming',
    progress_pct: 0,
    due_date: '2026-10-05T23:59:59Z',
    completed_at: null,
    tasks_count: 4,
    completed_tasks_count: 0,
    description: 'Timed 3-hour mock exams with peer grading and targeted knowledge-gap review.',
    created_at: '2026-09-20T08:00:00Z',
  },
  {
    id: 'mile_5',
    user_id: 'user_sahil_01',
    team_id: null,
    title: 'Final Submission & Internal Exams',
    category: 'Evaluation',
    status: 'upcoming',
    progress_pct: 0,
    due_date: '2026-10-10T23:59:59Z',
    completed_at: null,
    tasks_count: 3,
    completed_tasks_count: 0,
    description: 'Semester internal examination series and capstone project milestone 1 demonstration.',
    created_at: '2026-09-20T08:00:00Z',
  },
];

export const INITIAL_DISCUSSIONS: DiscussionMessage[] = [
  {
    id: 'disc_1',
    team_id: 'team_maths_survivors',
    user_id: 'user_arun_02',
    user_name: 'Arun Kumar',
    user_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    content: 'Hey everyone! I uploaded the Integration Formula Sheet to our shared resources. It has all the trigonometric substitutions worked out step-by-step.',
    created_at: '2026-09-26T14:15:00Z',
    attachments: [
      { name: 'Integration Formula Sheet.pdf', url: '#', size: '2.4 MB', type: 'pdf' },
    ],
  },
  {
    id: 'disc_2',
    team_id: 'team_maths_survivors',
    user_id: 'user_neha_03',
    user_name: 'Neha Roy',
    user_avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    content: 'Awesome Arun, thank you! I am going over Fourier series transforms today. Should we do a group call on Monday evening to solve sample exam questions together?',
    created_at: '2026-09-26T15:30:00Z',
    attachments: null,
  },
  {
    id: 'disc_3',
    team_id: 'team_maths_survivors',
    user_id: 'user_sahil_01',
    user_name: 'Sahil Doe (You)',
    user_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    content: 'Count me in for Monday! I can walk through the Differential Equations shortcuts and we can tackle the difficult integration problems together.',
    created_at: '2026-09-26T16:05:00Z',
    attachments: null,
  },
];

export const INITIAL_ACTIVITIES: TeamActivityItem[] = [
  {
    id: 'act_1',
    team_id: 'team_maths_survivors',
    user_name: 'Sahil Doe',
    user_avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    action_type: 'task_completed',
    description: 'completed task',
    target_title: 'Differential Equations Formula Cheatsheet',
    created_at: '2026-09-27T09:30:00Z',
  },
  {
    id: 'act_2',
    team_id: 'team_maths_survivors',
    user_name: 'Arun Kumar',
    user_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    action_type: 'resource_uploaded',
    description: 'uploaded a new resource',
    target_title: 'Integration Formula Sheet.pdf',
    created_at: '2026-09-26T14:15:00Z',
  },
  {
    id: 'act_3',
    team_id: 'team_maths_survivors',
    user_name: 'Neha Roy',
    user_avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    action_type: 'discussion_posted',
    description: 'posted in discussion',
    target_title: 'Monday Study Session proposal',
    created_at: '2026-09-26T15:30:00Z',
  },
  {
    id: 'act_4',
    team_id: 'team_maths_survivors',
    user_name: 'Neha Roy',
    user_avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    action_type: 'member_joined',
    description: 'joined the team via invite code',
    target_title: 'Maths Survivors',
    created_at: '2026-09-12T16:20:00Z',
  },
];

export const INITIAL_RESOURCES: ResourceItem[] = [
  {
    id: 'res_1',
    title: 'Integration Complete Formula & Substitution Guide',
    file_name: 'Integration_Formulas_2026.pdf',
    file_type: 'pdf',
    file_size_bytes: 2450000,
    file_size_formatted: '2.4 MB',
    storage_path: 'resources/math/Integration_Formulas_2026.pdf',
    url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    uploader_id: 'user_arun_02',
    uploader_name: 'Arun Kumar',
    team_id: 'team_maths_survivors',
    team_name: 'Maths Survivors',
    folder: 'Mathematics',
    category: 'documents',
    is_shared: true,
    created_at: '2026-09-26T14:10:00Z',
  },
  {
    id: 'res_2',
    title: 'Applied Physics Thermodynamics Lecture Notes',
    file_name: 'Thermodynamics_Lecture_Notes.docx',
    file_type: 'docx',
    file_size_bytes: 1840000,
    file_size_formatted: '1.8 MB',
    storage_path: 'resources/physics/Thermodynamics_Lecture_Notes.docx',
    url: '#',
    uploader_id: 'user_sahil_01',
    uploader_name: 'Sahil Doe',
    team_id: null,
    team_name: null,
    folder: 'Physics',
    category: 'documents',
    is_shared: false,
    created_at: '2026-09-25T11:20:00Z',
  },
  {
    id: 'res_3',
    title: 'Fourier Series Signal Filtering Presentation Deck',
    file_name: 'Fourier_Analysis_Presentation.pptx',
    file_type: 'pptx',
    file_size_bytes: 5200000,
    file_size_formatted: '5.2 MB',
    storage_path: 'resources/math/Fourier_Analysis_Presentation.pptx',
    url: '#',
    uploader_id: 'user_neha_03',
    uploader_name: 'Neha Roy',
    team_id: 'team_maths_survivors',
    team_name: 'Maths Survivors',
    folder: 'Presentations',
    category: 'presentations',
    is_shared: true,
    created_at: '2026-09-24T16:45:00Z',
  },
  {
    id: 'res_4',
    title: 'MIT OpenCourseWare: Partial Differential Equations Video Series',
    file_name: 'MIT_OCW_PDE_Lectures',
    file_type: 'link',
    file_size_bytes: 0,
    file_size_formatted: 'External Link',
    storage_path: '',
    url: 'https://ocw.mit.edu/courses/mathematics/',
    uploader_id: 'user_neha_03',
    uploader_name: 'Neha Roy',
    team_id: 'team_maths_survivors',
    team_name: 'Maths Survivors',
    folder: 'Video References',
    category: 'links',
    is_shared: true,
    created_at: '2026-09-23T10:00:00Z',
  },
  {
    id: 'res_5',
    title: 'Smart Agriculture Sensor Readings & Calibration Data',
    file_name: 'Soil_Moisture_Readings_Sep.xlsx',
    file_type: 'xlsx',
    file_size_bytes: 890000,
    file_size_formatted: '890 KB',
    storage_path: 'resources/agri/Soil_Moisture_Readings_Sep.xlsx',
    url: '#',
    uploader_id: 'user_sahil_01',
    uploader_name: 'Sahil Doe',
    team_id: 'team_smart_agri',
    team_name: 'Smart Agriculture Research',
    folder: 'Telemetry Data',
    category: 'spreadsheets',
    is_shared: true,
    created_at: '2026-09-22T08:30:00Z',
  },
  {
    id: 'res_6',
    title: 'Interferometer Optical Pattern Diagram',
    file_name: 'Interferometer_Optics_Diagram.png',
    file_type: 'image',
    file_size_bytes: 1420000,
    file_size_formatted: '1.4 MB',
    storage_path: 'resources/physics/Interferometer_Optics_Diagram.png',
    url: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=800&auto=format&fit=crop&q=80',
    uploader_id: 'user_sahil_01',
    uploader_name: 'Sahil Doe',
    team_id: null,
    team_name: null,
    folder: 'Physics Lab',
    category: 'images',
    is_shared: false,
    created_at: '2026-09-21T14:15:00Z',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_1',
    user_id: 'user_sahil_01',
    type: 'deadline_approaching',
    title: 'Deadline Approaching',
    message: 'Integration by Parts Problem Set is due tomorrow at 6:00 PM.',
    link: '/progress',
    is_read: false,
    created_at: '2026-09-27T08:00:00Z',
  },
  {
    id: 'notif_2',
    user_id: 'user_sahil_01',
    type: 'team_activity',
    title: 'New Discussion in Maths Survivors',
    message: 'Arun Kumar posted a new message with an attached formula sheet.',
    link: '/teams/team_maths_survivors?tab=discussion',
    is_read: false,
    created_at: '2026-09-26T14:16:00Z',
  },
  {
    id: 'notif_3',
    user_id: 'user_sahil_01',
    type: 'resource_shared',
    title: 'Resource Shared',
    message: 'Neha Roy shared "Fourier Series Presentation Deck" with Maths Survivors.',
    link: '/resources',
    is_read: true,
    created_at: '2026-09-24T16:46:00Z',
  },
  {
    id: 'notif_4',
    user_id: 'user_sahil_01',
    type: 'team_join',
    title: 'Member Joined Team',
    message: 'Neha Roy joined your team "Maths Survivors".',
    link: '/teams/team_maths_survivors?tab=members',
    is_read: true,
    created_at: '2026-09-12T16:20:00Z',
  },
];

export const INITIAL_BREAK_ACTIVITIES = [
  {
    id: 'act_breath_box',
    title: '2-Minute Box Breathing Reset',
    duration_minutes: 2,
    category: 'breathing' as const,
    description: 'A rhythmic 4-second breathing pattern used to settle focus, slow heart rate, and clear mental tension.',
    steps: [
      'Inhale slowly through your nose for 4 seconds',
      'Gently hold your breath for 4 seconds',
      'Exhale smoothly through your mouth for 4 seconds',
      'Hold empty for 4 seconds, then repeat for 4 cycles'
    ],
  },
  {
    id: 'act_screen_20',
    title: '20-20-20 Eye & Screen Relief',
    duration_minutes: 2,
    category: 'screen_reset' as const,
    description: 'Relieve digital eye strain and optic fatigue by redirecting focal distance.',
    steps: [
      'Shift your gaze away from all monitors and phone screens',
      'Focus on an object at least 20 feet (6 meters) away',
      'Blink slowly and relax your eyebrow muscles for 20 seconds',
      'Gently roll your shoulders backward 5 times'
    ],
  },
  {
    id: 'act_desk_stretch',
    title: '5-Minute Posture & Spine Stretch',
    duration_minutes: 5,
    category: 'movement' as const,
    description: 'Release tension in neck, shoulders, and lower back caused by prolonged study desk posture.',
    steps: [
      'Slow neck tilts from ear to shoulder (30 seconds each side)',
      'Interlace fingers behind back and gently open your chest',
      'Seated spinal twist looking over your right, then left shoulder',
      'Wrist and forearm extension flexes'
    ],
  },
  {
    id: 'act_hydration',
    title: 'Hydration & Mindful Pause',
    duration_minutes: 3,
    category: 'hydration' as const,
    description: 'Proper hydration sustains cognitive stamina and prevents mid-study fatigue.',
    steps: [
      'Stand up and step away from your study workspace',
      'Drink a full glass of cool or room-temperature water',
      'Take 3 deep breaths while standing tall'
    ],
  },
  {
    id: 'act_reflection',
    title: '3-Minute Micro-Win Reflection',
    duration_minutes: 3,
    category: 'reflection' as const,
    description: 'Acknowledge one concept or problem you progressed on today to maintain constructive momentum.',
    steps: [
      'Jot down or mentally note 1 task or concept you moved forward',
      'Remind yourself that understanding complex topics is an iterative process',
      'Identify the single next small step when you return'
    ],
  },
];

export const INITIAL_SUPPORT_RESOURCES = [
  {
    id: 'sup_math_lab',
    title: 'Peer Tutoring & Mathematics Learning Lab',
    category: 'Academic Support' as const,
    description: 'Free peer-led walk-in tutoring and collaborative problem-solving for calculus, algebra, and physics.',
    url: '/subjects',
    availability: 'Mon - Fri, 2:00 PM – 6:00 PM',
  },
  {
    id: 'sup_study_skills',
    title: 'Study Methods & Spaced Repetition Reference',
    category: 'Study & Learning Support' as const,
    description: 'Guides on active recall, Pomodoro cycles, and structured brain dump planning.',
    url: '/resources',
    availability: 'Digital Guide • Always Available',
  },
  {
    id: 'sup_peer_network',
    title: 'Student Peer Study Cohorts',
    category: 'Peer Mentoring' as const,
    description: 'Connect with classmates for shared exam preparation and project accountability.',
    url: '/teams',
    availability: 'Available via Team Directory',
  },
  {
    id: 'sup_library_pods',
    title: 'Quiet Study Pods & Collaborative Spaces',
    category: 'Campus Advising' as const,
    description: 'Library group rooms equipped with digital whiteboards and charging hubs.',
    url: '/resources',
    availability: 'Campus Library • 8:00 AM – 10:00 PM',
  },
];

export const INITIAL_TEAM_CHECKINS = [
  {
    id: 'tc_1',
    team_id: 'team_maths_survivors',
    user_id: 'user_arun_02',
    user_name: 'Arun Kumar',
    status: 'making_progress' as const,
    note: 'Working on Fourier Transform step 3',
    created_at: '2026-09-27T10:15:00Z',
  },
  {
    id: 'tc_2',
    team_id: 'team_maths_survivors',
    user_id: 'user_neha_03',
    user_name: 'Neha Roy',
    status: 'taking_break' as const,
    note: 'Stepping away for a 10m tea break',
    created_at: '2026-09-27T10:20:00Z',
  },
];

